# Generated by Django 5.0.4 on 2024-04-17 10:16

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_kullaniciicerik_icerik_dosya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullaniciicerik',
            name='icerik_dosya',
        ),
        migrations.AlterField(
            model_name='kullaniciicerik',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.kullanici_dosya_yolu),
        ),
        migrations.AlterField(
            model_name='kullaniciicerik',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.kullanici_dosya_yolu),
        ),
    ]
