# Generated by Django 5.0.4 on 2024-04-17 11:00

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_kullaniciicerik_icerik_dosya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullaniciicerik',
            name='icerik_dosya',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.kullanici_dosya_yolu),
        ),
    ]
